[19/May/2022 13:12:32] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[19/May/2022 13:12:32] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[19/May/2022 13:12:32] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[19/May/2022 13:12:32] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[19/May/2022 13:12:32] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[19/May/2022 13:12:32] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[19/May/2022 13:12:32] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[19/May/2022 13:12:32] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[19/May/2022 13:12:32] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[19/May/2022 13:12:32] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[19/May/2022 13:12:32] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[19/May/2022 13:12:32] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[19/May/2022 15:11:45] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[19/May/2022 15:11:45] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[19/May/2022 15:11:45] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[19/May/2022 15:11:45] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[19/May/2022 15:11:45] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[19/May/2022 15:11:45] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[19/May/2022 15:11:45] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[19/May/2022 15:11:45] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[19/May/2022 15:11:45] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[19/May/2022 15:11:45] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[19/May/2022 15:11:45] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[19/May/2022 15:11:45] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[19/May/2022 15:20:20] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[19/May/2022 15:20:20] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[19/May/2022 15:20:20] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[19/May/2022 15:20:20] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[19/May/2022 15:20:21] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[19/May/2022 15:20:21] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[19/May/2022 15:20:21] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[19/May/2022 15:20:21] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[19/May/2022 15:20:21] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[19/May/2022 15:20:21] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[19/May/2022 15:20:21] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[19/May/2022 15:20:21] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 08:19:31] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[20/May/2022 08:19:31] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[20/May/2022 08:19:31] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[20/May/2022 08:19:31] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[20/May/2022 08:19:31] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 08:19:31] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 08:19:31] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 08:19:31] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 08:19:31] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 08:19:31] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 08:19:31] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 08:19:31] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 11:11:17] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[20/May/2022 11:11:17] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[20/May/2022 11:11:17] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[20/May/2022 11:11:17] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[20/May/2022 11:11:17] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 11:11:17] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 11:11:17] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 11:11:17] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 11:11:17] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 11:11:17] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 11:11:17] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 11:11:17] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 11:12:02] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[20/May/2022 11:12:02] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[20/May/2022 11:12:02] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[20/May/2022 11:12:02] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[20/May/2022 11:12:02] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 11:12:02] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 11:12:02] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 11:12:02] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 11:12:02] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 11:12:02] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 11:12:02] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 11:12:02] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 11:19:35] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[20/May/2022 11:19:35] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[20/May/2022 11:19:35] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[20/May/2022 11:19:35] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'AuthViewset' should either include a `queryset` attribute, or override the `get_queryset()` method.
[20/May/2022 11:19:35] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 11:19:35] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 11:19:35] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 11:19:35] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 11:19:35] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 11:19:35] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 11:19:35] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 11:19:35] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[20/May/2022 12:52:54] ERROR [root:74] None - /var/www/html/emmy/Drf-Auth-SYS/core/api_views.py
[21/May/2022 08:23:19] ERROR [root:85] None - /var/www/html/emmy/Drf-Auth-SYS/core/api_views.py
[21/May/2022 12:46:05] ERROR [root:112] None - /var/www/html/emmy/Drf-Auth-SYS/core/api_views.py
[22/May/2022 10:12:07] ERROR [root:149] None - /var/www/html/emmy/Drf-Auth-SYS/core/api_views.py
[22/May/2022 10:12:57] ERROR [root:151] None - /var/www/html/emmy/Drf-Auth-SYS/core/api_views.py
[22/May/2022 10:13:53] ERROR [root:151] None - /var/www/html/emmy/Drf-Auth-SYS/core/api_views.py
[22/May/2022 10:13:53] ERROR [root:151] None - /var/www/html/emmy/Drf-Auth-SYS/core/api_views.py
[22/May/2022 12:08:43] ERROR [root:117] None - /var/www/html/emmy/Drf-Auth-SYS/core/api_views.py
[23/May/2022 10:44:48] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[23/May/2022 10:44:48] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[23/May/2022 10:44:48] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[23/May/2022 10:44:48] WARNING [drf_yasg.inspectors.base:44] view's AuthViewset raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AuthViewset' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[23/May/2022 10:55:57] ERROR [root:120] None - /var/www/html/emmy/Drf-Auth-SYS/core/api_views.py
[23/May/2022 11:01:57] ERROR [root:120] None - /var/www/html/emmy/Drf-Auth-SYS/core/api_views.py
[23/May/2022 11:11:14] ERROR [root:120] None - /var/www/html/emmy/Drf-Auth-SYS/core/api_views.py
[23/May/2022 11:17:32] ERROR [root:120] None - /var/www/html/emmy/Drf-Auth-SYS/core/api_views.py
[23/May/2022 14:04:24] ERROR [root:117] None - /var/www/html/emmy/Drf-Auth-SYS/core/api_views.py
[23/May/2022 14:11:13] ERROR [root:118] None - /var/www/html/emmy/Drf-Auth-SYS/core/api_views.py
[23/May/2022 15:26:49] ERROR [django.request:241] Internal Server Error: /api/docs/ - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/utils/log.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/views.py", line 94, in get
    schema = generator.get_schema(request, self.public)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 246, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 404, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 432, in get_operation
    overrides = self.get_overrides(view, method)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 483, in get_overrides
    return copy.deepcopy(overrides)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 161, in deepcopy
    rv = reductor(4)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/response.py", line 95, in __getstate__
    state = super().__getstate__()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/template/response.py", line 60, in __getstate__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be pickled.
[23/May/2022 15:26:49] ERROR [django.server:187] "GET /api/docs/?format=openapi HTTP/1.1" 500 163497 - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/core/servers/basehttp.py
[23/May/2022 15:29:48] ERROR [django.request:241] Internal Server Error: /api/docs/ - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/utils/log.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/views.py", line 94, in get
    schema = generator.get_schema(request, self.public)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 246, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 404, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 432, in get_operation
    overrides = self.get_overrides(view, method)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 483, in get_overrides
    return copy.deepcopy(overrides)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 161, in deepcopy
    rv = reductor(4)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/response.py", line 95, in __getstate__
    state = super().__getstate__()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/template/response.py", line 60, in __getstate__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be pickled.
[23/May/2022 15:29:48] ERROR [django.server:187] "GET /api/docs/?format=openapi HTTP/1.1" 500 163475 - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/core/servers/basehttp.py
[23/May/2022 15:31:07] ERROR [django.request:241] Internal Server Error: /api/docs/ - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/utils/log.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/views.py", line 94, in get
    schema = generator.get_schema(request, self.public)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 246, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 404, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 432, in get_operation
    overrides = self.get_overrides(view, method)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 483, in get_overrides
    return copy.deepcopy(overrides)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 161, in deepcopy
    rv = reductor(4)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/response.py", line 95, in __getstate__
    state = super().__getstate__()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/template/response.py", line 60, in __getstate__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be pickled.
[23/May/2022 15:31:07] ERROR [django.server:187] "GET /api/docs/?format=openapi HTTP/1.1" 500 163485 - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/core/servers/basehttp.py
[23/May/2022 15:32:52] ERROR [django.request:241] Internal Server Error: /api/docs/ - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/utils/log.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/views.py", line 94, in get
    schema = generator.get_schema(request, self.public)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 246, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 404, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 432, in get_operation
    overrides = self.get_overrides(view, method)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 483, in get_overrides
    return copy.deepcopy(overrides)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 161, in deepcopy
    rv = reductor(4)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/response.py", line 95, in __getstate__
    state = super().__getstate__()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/template/response.py", line 60, in __getstate__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be pickled.
[23/May/2022 15:32:52] ERROR [django.server:187] "GET /api/docs/?format=openapi HTTP/1.1" 500 163497 - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/core/servers/basehttp.py
[23/May/2022 15:34:07] ERROR [django.request:241] Internal Server Error: /api/docs/ - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/utils/log.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/views.py", line 94, in get
    schema = generator.get_schema(request, self.public)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 246, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 404, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 432, in get_operation
    overrides = self.get_overrides(view, method)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 483, in get_overrides
    return copy.deepcopy(overrides)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 161, in deepcopy
    rv = reductor(4)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/response.py", line 95, in __getstate__
    state = super().__getstate__()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/template/response.py", line 60, in __getstate__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be pickled.
[23/May/2022 15:34:07] ERROR [django.server:187] "GET /api/docs/?format=openapi HTTP/1.1" 500 163497 - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/core/servers/basehttp.py
[23/May/2022 15:44:06] ERROR [django.request:241] Internal Server Error: /api/docs/ - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/utils/log.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/views.py", line 94, in get
    schema = generator.get_schema(request, self.public)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 246, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 404, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 432, in get_operation
    overrides = self.get_overrides(view, method)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 483, in get_overrides
    return copy.deepcopy(overrides)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 161, in deepcopy
    rv = reductor(4)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/response.py", line 95, in __getstate__
    state = super().__getstate__()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/template/response.py", line 60, in __getstate__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be pickled.
[23/May/2022 15:44:06] ERROR [django.server:187] "GET /api/docs/?format=openapi HTTP/1.1" 500 163497 - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/core/servers/basehttp.py
[23/May/2022 16:04:25] ERROR [django.request:241] Internal Server Error: /api/docs/ - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/utils/log.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/views.py", line 94, in get
    schema = generator.get_schema(request, self.public)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 246, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 404, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 432, in get_operation
    overrides = self.get_overrides(view, method)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 483, in get_overrides
    return copy.deepcopy(overrides)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 161, in deepcopy
    rv = reductor(4)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/response.py", line 95, in __getstate__
    state = super().__getstate__()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/template/response.py", line 60, in __getstate__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be pickled.
[23/May/2022 16:04:25] ERROR [django.server:187] "GET /api/docs/?format=openapi HTTP/1.1" 500 163497 - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/core/servers/basehttp.py
[24/May/2022 10:21:19] ERROR [django.request:241] Internal Server Error: /api/docs/ - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/utils/log.py
Traceback (most recent call last):
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/views.py", line 94, in get
    schema = generator.get_schema(request, self.public)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 246, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 404, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 432, in get_operation
    overrides = self.get_overrides(view, method)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/drf_yasg/generators.py", line 483, in get_overrides
    return copy.deepcopy(overrides)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 161, in deepcopy
    rv = reductor(4)
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/rest_framework/response.py", line 95, in __getstate__
    state = super().__getstate__()
  File "/var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/template/response.py", line 60, in __getstate__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be pickled.
[24/May/2022 10:21:19] ERROR [django.server:187] "GET /api/docs/?format=openapi HTTP/1.1" 500 163497 - /var/www/environments/emmy/Auth-system/lib/python3.9/site-packages/django/core/servers/basehttp.py
